app/automation/routes.py
from flask import render_template, request, Blueprint
from app import db

automation_bp = Blueprint('automation_bp', __name__, template_folder='templates')

@automation_bp.route("/automation/signup", methods=["GET", "POST"])
def signupform():
    if request.method == "POST":
        returndict = {}
        email = request.form['email']
        password = request.form['password']
        country = request.form['country']
        sports = request.form.getlist('sports')
        about = request.form['about']
        coupon = request.form['coupon']

        if request.form.get('general_newsletter'):
            returndict['general_newsletter'] = True

        if request.form.get('technical_newsletter'):
            returndict['technical_newsletter'] = True

        returndict['email'] = email
        returndict['password'] = password
        returndict['country'] = country
        returndict['sports'] = sports
        returndict['about'] = about
        returndict['coupon'] = coupon



        print(returndict)

        return render_template('automation/signupresults.html', title='Signup', results=returndict)



    return render_template('automation/signup.html', title='Signup')

app/automation/templates/automation/signup.html
{% extends "layout.html" %}
{% block content %}
<div class="row mt-5">
  <div class="col-sm-5 mx-auto mb-4">
    <div class="content-section">
        <form method="POST" action="{{ url_for('automation_bp.signupform') }}">
          <fieldset>
            <legend>Signup Form</legend>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group">
              <label for="exampleSelect1">Country</label>
              <select name="country" class="form-control" id="countrySelect">
                <option value=''>Select One</option>
                <option>Australia</option>
                <option>Canada</option>
                <option>India</option>
                <option>United States</option>
                <option>United Kingdom</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleSelect2">Select favorite sports (multiple allowed)</label>
              <select name="sports" multiple="" class="form-control" id="exampleSelect2">
                <option>American Football</option>
                <option>Badminton</option>
                <option>Basketball</option>
                <option>Cricket</option>
                <option>Golf</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleTextarea">About yourself</label>
              <textarea name="about" class="form-control" id="exampleTextarea" rows="3"></textarea>
            </div>

            <fieldset class="form-group">
              <legend>Gender</legend>
              <div class="form-check">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" name="gender" id="optionsRadios1" value="male" checked="">
                  Male
                </label>
              </div>
              <div class="form-check">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" name="gender" id="optionsRadios2" value="female">
                  Female
                </label>
              </div>
            </fieldset>
            <fieldset class="form-group">
              <legend>Subscribe to newsletter </legend>
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" value="general_newsletter" checked="" name="general_newsletter">
                  Subscribe to general newsletter
                </label>
              </div>
              <div class="form-check disabled">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" value="technical_newsletter" name="technical_newsletter">
                  Subscribe to technical newsletter
                </label>
              </div>
            </fieldset>

            <fieldset class="form-group">
                <div class="form-group">
                    <label for="couponInput">Enter Coupon Code</label>
                    <input name="coupon" type="text" class="form-control" id="couponInput" aria-describedby="emailHelp" placeholder="Enter coupon code">
                </div>
                <button id="couponbutton" onclick="applycoupon()" type="button" class="btn btn-warning">Apply Coupon</button>
                <div class="coupontext mt-2"></div>
            </fieldset>

            <fieldset class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
          </fieldset>
        </form>
    </div>
  </div>
</div>

<script>
function applycoupon() {
   var btn = document.getElementById("couponbutton");
   btn.disabled = true;
   btn.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Verifying Coupon...'


    var couponValue = document.getElementById("couponInput").value;

    var newDiv1 = document.createElement("p");
    var newContent1 = document.createTextNode("");
    newDiv1.appendChild(newContent1);
    newDiv1.className = "ajax-output-example-class";
    $('.coupontext').html(newDiv1);

    if ( couponValue == "AUTOMATION") {
      var newDiv = document.createElement("p");
      var newContent = document.createTextNode("Coupon Applied Successfully !");
      newDiv.appendChild(newContent);
      newDiv.className = "ajax-output-example-class text-success";
    } else {
      var newDiv = document.createElement("p");
      var newContent = document.createTextNode("Invalid Coupon !");
      newDiv.appendChild(newContent);
      newDiv.className = "ajax-output-example-class text-danger";
    }

    setTimeout(function(){
      $('.coupontext').html(newDiv);
      btn.disabled = false;
      btn.innerHTML = 'Apply Coupon';
    },5000);

  }
</script>
{% endblock content %}

app/automation/templates/automation/signupresults.html
{% extends "layout.html" %}
{% block content %}
<div class="row mt-5">
  <div class="col-sm-5 mx-auto mb-4">
    <div class="content-section">
      <legend>Signup Form Results</legend>
      <table class="table">
        {% for k, v in results.items() %}
        <tr>
        <td>{{k}}</td>
        <td>{{v}}</td>
        </tr>
        {% endfor %}
        </table>
    </div>
  </div>
</div>
{% endblock content %}