app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from app.config import Config

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'auth_bp.login'
login_manager.login_message_category = 'info'
mail = Mail()

def create_app(config_class=Config):
    flask_app = Flask(__name__)
    flask_app.config.from_object(Config)

    db.init_app(flask_app)
    migrate.init_app(flask_app,db)
    bcrypt.init_app(flask_app)
    login_manager.init_app(flask_app)
    mail.init_app(flask_app)

    from app.auth.routes import auth_bp
    from app.main.routes import main_bp
    from app.errors.handlers import errors_bp
    from app.automation.routes import automation_bp
    from app.commands import cmd_bp

    flask_app.register_blueprint(auth_bp)
    flask_app.register_blueprint(main_bp)
    flask_app.register_blueprint(errors_bp)
    flask_app.register_blueprint(automation_bp)
    flask_app.register_blueprint(cmd_bp)

    return flask_app

app/automation/routes.py
from flask import render_template, request, Blueprint
from app import db

automation_bp = Blueprint('automation_bp', __name__, template_folder='templates')

@automation_bp.route("/automation/signup", methods=["GET", "POST"])
def signupform():
    if request.method == "POST":
        returndict = {}
        email = request.form['email']
        password = request.form['password']
        country = request.form['country']
        sports = request.form.getlist('sports')
        about = request.form['about']
        coupon = request.form['coupon']

        if request.form.get('general_newsletter'):
            returndict['general_newsletter'] = True

        if request.form.get('technical_newsletter'):
            returndict['technical_newsletter'] = True

        returndict['email'] = email
        returndict['password'] = password
        returndict['country'] = country
        returndict['sports'] = sports
        returndict['about'] = about
        returndict['coupon'] = coupon



        print(returndict)

        return render_template('automation/signupresults.html', title='Signup', results=returndict)



    return render_template('automation/signup.html', title='Signup')

app/main/routes.py
from flask import render_template, request, Blueprint
from app import db

main_bp = Blueprint('main_bp', __name__)

@main_bp.route("/")
@main_bp.route("/home")
def home():
    return render_template('home.html', title='Home')

@main_bp.route("/about")
def about():
    return render_template('about.html', title='About')

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/darkly/bootstrap.min.css" rel="stylesheet" id="styles">
    <script>window.$q=[];window.$=window.jQuery=function(a){window.$q.push(a);};</script>

    {% if title %}
        <title>{{ config.APP_NAME }} - {{ title }}</title>
    {% else %}
        <title>{{ config.APP_NAME }}</title>
    {% endif %}
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}" >
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc="   crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/main.js') }}"></script>
</body>

</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
      <a class="navbar-brand mr-4" href="/">{{ config.APP_NAME }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{{ url_for('main_bp.home') }}">Home</a>
          <a class="nav-item nav-link" href="{{ url_for('main_bp.about') }}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('auth_bp.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('auth_bp.logout') }}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{{ url_for('auth_bp.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('auth_bp.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
      <div class="custom-control custom-switch">
          <input type="checkbox" class="custom-control-input" id="customSwitch1" checked="">
          <label class="custom-control-label" style="color:rgba(255,255,255,0.5)" for="customSwitch1">Dark Theme</label>
    </div>
  </div>
</nav>